DROP TABLE IF EXISTS Tutkija CASCADE;

DROP TABLE IF EXISTS Kenttatutkimusraportti CASCADE;

DROP TABLE IF EXISTS Nayte CASCADE;

DROP TABLE IF EXISTS Naytteenottopaikka CASCADE;

DROP TABLE IF EXISTS Vesisto CASCADE;

DROP TABLE IF EXISTS Kohde CASCADE;
